//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoAmIBotReloaded
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.QuestionsAsked = 0;
            this.QuestionsAnswered = 0;
        }
    
        public long Id { get; set; }
        public string Role { get; set; }
        public int Placement { get; set; }
        public int QuestionsAsked { get; set; }
        public int QuestionsAnswered { get; set; }
        public long GameId { get; set; }
        public int Guessed { get; set; }
        public bool GuessedRole { get; set; }
    
        public virtual Player ChoseRoleFor { get; set; }
        public virtual Player RoleWasChosenBy { get; set; }
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
